# Generated by Django 4.1.7 on 2023-04-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dept",
            name="dname",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="dept",
            name="loc",
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("empno", models.IntegerField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=30)),
                ("job", models.CharField(max_length=30)),
                ("mgr", models.IntegerField()),
                ("hiredate", models.DateField()),
                ("sal", models.IntegerField()),
                ("comm", models.IntegerField()),
                (
                    "departno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dept"
                    ),
                ),
            ],
        ),
    ]
